ALTER TYPE "AdjustmentType" ADD VALUE 'MADRUGADA';
ALTER TABLE "Payment" ADD COLUMN "madrugadaTotal" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "AppSettings" ADD COLUMN "valorFixoMadrugada" DECIMAL(10,2) NOT NULL DEFAULT 0;
